### ISSUE TITLE
Getting from here to a place where roll-call can replace 75% of POTS calls

### ISSUE THREAD

**Issue by faddat** [mikeal/peer-call#100] opened 2017-01-08 23:34 UTC
I agree.  Calls should be free, and this is a really great start!

I'm just sort of pondering.... how can we go from this admirable start to something that can genuinely replace POTS and deliver similar reliability?  

How do we get it work reliably (not "skype-reliably"-- POTS or better-reliably) in a number of different network conditions, and therefore call qualities?

It's an awesome project, just... throwing out some questions....

**Comment by mikeal** [comment] 2017-01-09 08:24
In terms of call quality I find that it's already better than skype for 2 person calls. The problem is the "reliability" part of the equation.

Right now @feross has been generous enough to let us piggyback on his TURN account with Twilio. At some point that will have to be turned off, and that'll lose about 10% of the existing callers. It's not economical to provide free TURN service at a certain scale :(

I've considered some alternatives distribution mechanism for a "push to talk" system using MediaRecorder but I'm afraid that it just isn't possible until we get some platform improvements in the browser.

There's a few strategies I'm taking towards increasing adoption:

* One is to push on the web platform as much as I can to expose limitations and then try to get the platform improved to overcome them. We're already seeing a bunch of those rough edges.
* Another thing I'm in the middle of is a big refactoring of the code to make the entire system more embeddable. This will make it trivial to embed an iframe, or to require('roll-call') in your own code, and embed an audio call. That opens up a whole new dimension of adoption.
* I'm also slowly putting together a list of features I'm going to integrate into some kind of a "Roll Call Pro" service. Basically, all the things that require more infrastructure than can be sustained for free (cloud storage of calls of each track, "voicemail" service, etc) will end up in this service that should pay its own bills.

**Comment by faddat** [comment] 2017-01-10 01:20
I'll try putting a TURN server up on my cluster.  My cluster is a toy, so it doesn't need to be economical :).

**Comment by mikeal** [comment] 2017-01-10 02:20
That would be great :)

From the research I've done so far doing multi-tenant TURN is actually not very simple so feel free to check in here if you hit any bumps, there's a few people around that I think have done similar research.

**Comment by mikeal** [comment] 2017-09-19 17:50
Closing until we have more direction on how to proceed.

I've been focused on providing a few things POTS can't do (file transfer, embedabilty, etc.)

**Closed as completed by mikeal** 2017-09-19 17:50 UTC
